# Generated by Django 5.2.1 on 2025-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='thana',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='union',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='village',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='zilla',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
