# Generated by Django 5.2.1 on 2025-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0002_userpersonalinfo_thana_userpersonalinfo_union_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_insurance_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_our_agent',
            field=models.BooleanField(default=False),
        ),
    ]
