# Generated by Django 5.2.1 on 2025-05-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0003_user_is_insurance_agent_user_is_our_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_our_agent',
            new_name='is_insurecow_agent',
        ),
    ]
