# Generated by Django 5.2.1 on 2025-05-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0004_rename_is_our_agent_user_is_insurecow_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_enterprise',
            field=models.ForeignKey(blank=True, help_text='Only Enterprise user can be assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_enterprise_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
