# Generated by Django 5.2.1 on 2025-05-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0005_user_parent_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enterprise_agent',
            field=models.BooleanField(default=False),
        ),
    ]
