# Generated by Django 5.2.1 on 2025-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0008_alter_token_access_token_alter_token_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernomineeinfo',
            name='relationship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
