# Generated by Django 5.2.1 on 2025-05-11 19:54

from django.db import migrations, models

import assetservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0008_alter_asset_refernce_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='refernce_id',
            new_name='reference_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, help_text='height', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='image_with_owner',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='last_date_of_calving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='pregnancy_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='height', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_bill',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_from',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='special_mark',
            field=models.FileField(upload_to=assetservice.models.asset_upload_path),
        ),
    ]
