# Generated by Django 5.2.1 on 2025-05-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0009_rename_refernce_id_asset_reference_id_asset_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='purchase_bill',
        ),
    ]
