# Generated by Django 5.2.1 on 2025-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0010_remove_asset_purchase_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
