# Generated by Django 5.2.1 on 2025-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0011_asset_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pregnancy_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
