# Generated by Django 5.2.1 on 2025-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0012_alter_asset_health_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='height', max_digits=6, null=True),
        ),
    ]
