# Generated by Django 5.2.1 on 2025-05-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0013_alter_asset_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
