# Generated by Django 5.2.1 on 2025-05-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0002_alter_insuranceclaim_amount_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceperiod',
            name='category',
        ),
        migrations.RemoveField(
            model_name='insuranceperiod',
            name='company',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='premiumpercentage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='premiumpercentage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='premiumpercentage',
            name='insurance_type',
        ),
        migrations.AddField(
            model_name='insuranceperiod',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_periods', to='insuranceservice.insurancetype'),
            preserve_default=False,
        ),
    ]
