# Generated by Django 5.2.1 on 2025-05-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0004_delete_insuranceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinsurance',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
