# Generated by Django 5.2.1 on 2025-05-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0005_assetinsurance_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinsurance',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_percentage', models.FloatField()),
                ('insurance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_products', to='insuranceservice.insuranceperiod')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_products', to='insuranceservice.insurancetype')),
            ],
        ),
    ]
