# Generated by Django 5.2.1 on 2025-05-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0006_alter_assetinsurance_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='insurance_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_products', to='insuranceservice.insurancecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='insurance_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_products', to='insuranceservice.insurancecompany'),
            preserve_default=False,
        ),
    ]
