# Generated by Django 5.2.1 on 2025-05-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0007_insuranceproduct_insurance_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinsurance',
            name='insurance_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_insurances', to='insuranceservice.insuranceproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetinsurance',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinsurance',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
