# Generated by Django 5.2.1 on 2025-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0008_assetinsurance_insurance_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_muzzle',
            field=models.ImageField(blank=True, null=True, upload_to='claims/claim_muzzle/'),
        ),
    ]
