# Generated by Django 5.2.1 on 2025-05-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0014_alter_asset_purchase_amount'),
        ('insuranceservice', '0009_insuranceclaim_claim_muzzle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceclaim',
            old_name='created_bycreated_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='insured_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='assetservice.asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='reference_id',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='claim_documents',
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='asset/claim_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='insuranceservice.assetinsurance')),
            ],
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_documents',
            field=models.ManyToManyField(blank=True, related_name='claims', to='insuranceservice.claimdocument'),
        ),
    ]
