# Generated by Django 5.2.1 on 2025-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0014_alter_asset_purchase_amount'),
        ('insuranceservice', '0010_rename_created_bycreated_by_insuranceclaim_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='insured_asset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='assetservice.asset'),
        ),
    ]
