# Generated by Django 5.2.1 on 2025-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0012_alter_assetinsurance_insurance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinsurance',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
