# Generated by Django 5.2.1 on 2025-06-09 08:44

import django.db.models.deletion
import insuranceservice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0014_alter_assetinsurance_insurance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=100)),
                ('trx_date', models.DateField()),
                ('trx_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('MFS', 'MFS'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('trx_through', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assetInsuranceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_payments', to='insuranceservice.assetinsurance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trx_id', 'trx_through', 'assetInsuranceId')},
            },
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=insuranceservice.models.trx_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trx_documents', to='insuranceservice.paymentinformation')),
            ],
        ),
    ]
