# Generated by Django 5.2.1 on 2025-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0015_paymentinformation_transactiondocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinsurance',
            name='insurance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('additional_info_required', 'Additional Info Required'), ('application_approved', 'Application Approved'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('payment_verified', 'Payment Verified'), ('payment_failed', 'Payment Failed'), ('refunded', 'Refunded'), ('pending_payment_verification', 'Pending Payment Verification'), ('active', 'Active'), ('pending_activation', 'Pending Activation'), ('in_grace_period', 'In Grace Period'), ('suspended', 'Suspended'), ('lapsed', 'Lapsed'), ('expired', 'Expired'), ('renewal_due', 'Renewal Due'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('cancellation_requested', 'Cancellation Requested'), ('terminated', 'Terminated'), ('voided', 'Voided'), ('kyc_pending', 'KYC Pending'), ('kyc_verified', 'KYC Verified'), ('documents_pending', 'Documents Pending'), ('fraud_suspected', 'Fraud Suspected'), ('audit_required', 'Audit Required')], default='pending', max_length=255),
        ),
    ]
