# Generated by Django 5.2.1 on 2025-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0016_alter_assetinsurance_insurance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentinformation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='paymentinformation',
            unique_together={('trx_id', 'amount', 'trx_through', 'assetInsuranceId')},
        ),
    ]
