# Generated by Django 5.2.1 on 2025-06-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0017_alter_paymentinformation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
